name: github pages

on:
  push:
    branches:
      - main 
  pull_request:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install pandoc
        run: |
          #sudo apt update
          #sudo apt install -y pandoc
          #pandoc_git_tag="$(git ls-remote -q -t --refs https://github.com/jgm/pandoc.git | awk '/tags\/[0-9]/{sub("refs/tags/", ""); print $2 }' | awk '!/^$/' | sort -rV | head -n 1)"
          pandoc_git_tag=3.1.3
          curl -sLo- "https://github.com/jgm/pandoc/releases/download/${pandoc_git_tag}/pandoc-${pandoc_git_tag}-linux-amd64.tar.gz" | sudo tar xzf - --strip-components 2 -C /usr/local/bin --exclude="share"
          pandoc --version

      - name: Build
        run: make

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs
